specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: PoolFactory
    network: optimism
    source:
      address: "0x5e61a079A178f0E5784107a4963baAe0c5a680c6"
      abi: PoolFactory
      startBlock: 642351
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - FundCreated
      abis:
        - name: PoolFactory
          file: ./abis/PoolFactory.json
      eventHandlers:
        - event: FundCreated(address,bool,string,string,address,uint256,uint256,uint256)
          handler: handleFundCreated
      file: ./src/pool-factory.ts
  - kind: ethereum/contract
    name: PoolFactoryMoonlight
    network: optimism
    source:
      address: "0x5e61a079A178f0E5784107a4963baAe0c5a680c6"
      abi: PoolFactoryMoonlight
      startBlock: 6469716
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - FundCreated
      abis:
        - name: PoolFactoryMoonlight
          file: ./abis/PoolFactoryMoonlight.json
      eventHandlers:
        - event: FundCreated(address,bool,string,string,address,uint256,uint256,uint256,uint256)
          handler: handleFundCreated
      file: ./src/pool-factory-moonlight.ts
  - kind: ethereum
    name: PoolLimitOrderManager
    network: optimism
    source:
      address: "0x3bfe2a472d2964ea4070725b7fb0a868b3f08b63"
      abi: PoolLimitOrderManager
      startBlock: 135734000
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - AuthorizedKeeperAdded
        - AuthorizedKeeperRemoved
        - LimitOrderCreated
        - LimitOrderModified
        - SettlementOrderCreated
      abis:
        - name: PoolLimitOrderManager
          file: ./abis/PoolLimitOrderManager.json
        - name: PoolFactoryMoonlight
          file: ./abis/PoolFactoryMoonlight.json
      eventHandlers:
        - event: AuthorizedKeeperAdded(address)
          handler: handleAuthorizedKeeperAdded
        - event: AuthorizedKeeperRemoved(address)
          handler: handleAuthorizedKeeperRemoved
        - event: LimitOrderCreated(indexed address,indexed address,bytes32)
          handler: handleLimitOrderCreated
        - event: LimitOrderDeleted(indexed address,indexed address,bytes32)
          handler: handleLimitOrderDeleted
        - event: LimitOrderExecuted(indexed address,indexed address,bytes32)
          handler: handleLimitOrderExecuted
        - event: LimitOrderModified(indexed address,indexed address,bytes32)
          handler: handleLimitOrderModified
        - event: SettlementOrderCreated(indexed address)
          handler: handleSettlementOrderCreated
      file: ./src/pool-limit-order-manager.ts

templates:
  - kind: ethereum/contract
    name: PoolLogic
    network: optimism
    source:
      abi: PoolLogic
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Deposit
        - ManagerFeeMinted
        - TransactionExecuted
        - Transfer
        - Withdrawal
        - Pool
        - EntryFeeMinted
        - ExitFeeMinted
      abis:
        - name: PoolLogic
          file: ./abis/PoolLogic.json
        - name: PoolManagerLogic
          file: ./abis/PoolManagerLogic.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Deposit(address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleDeposit
        - event: ManagerFeeMinted(address,address,uint256,uint256,uint256,uint256)
          handler: handleManagerFeeMinted
        - event: TransactionExecuted(address,address,uint16,uint256)
          handler: handleTransactionExecuted
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Withdrawal(address,address,uint256,uint256,uint256,uint256,uint256,(address,uint256,bool)[],uint256)
          handler: handleWithdrawal
        - event: EntryFeeMinted(address,uint256)
          handler: handleEntryFeeMinted
        - event: ExitFeeMinted(address,uint256)
          handler: handleExitFeeMinted
      file: ./src/pool-logic.ts
