specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: PoolFactory
    network: matic
    source:
      address: "0xDd87eCdB10cFF7004276AAbAbd30e7a08F69bb53"
      abi: PoolFactory
      startBlock: 17364000
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - FundCreated
      abis:
        - name: PoolFactory
          file: ./abis/PoolFactory.json
      eventHandlers:
        - event: FundCreated(address,bool,string,string,address,uint256,uint256,uint256)
          handler: handleFundCreated
      file: ./src/pool-factory.ts
  - kind: ethereum/contract
    name: PoolFactoryMoonlight
    network: matic
    source:
      address: "0xDd87eCdB10cFF7004276AAbAbd30e7a08F69bb53"
      abi: PoolFactoryMoonlight
      startBlock: 27069574
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - FundCreated
      abis:
        - name: PoolFactoryMoonlight
          file: ./abis/PoolFactoryMoonlight.json
      eventHandlers:
        - event: FundCreated(address,bool,string,string,address,uint256,uint256,uint256,uint256)
          handler: handleFundCreated
      file: ./src/pool-factory-moonlight.ts

templates:
  - kind: ethereum/contract
    name: PoolLogic
    network: matic
    source:
      abi: PoolLogic
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Deposit
        - ManagerFeeMinted
        - TransactionExecuted
        - Transfer
        - Withdrawal
        - Pool
      abis:
        - name: PoolLogic
          file: ./abis/PoolLogic.json
        - name: PoolManagerLogic
          file: ./abis/PoolManagerLogic.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: Deposit(address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)
          handler: handleDeposit
        - event: ManagerFeeMinted(address,address,uint256,uint256,uint256,uint256)
          handler: handleManagerFeeMinted
        - event: TransactionExecuted(address,address,uint16,uint256)
          handler: handleTransactionExecuted
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Withdrawal(address,address,uint256,uint256,uint256,uint256,uint256,(address,uint256,bool)[],uint256)
          handler: handleWithdrawal
      file: ./src/pool-logic.ts
